package com.example.demodb.core.model.security;

import javax.persistence.*;
import java.io.Serializable;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UsersRoles generated by hbm2java
 */
@Entity
@Table(name = "usuario_rol")
public class UsuarioRol implements Serializable {

	private static final long serialVersionUID = -2602934385470272950L;
	private Integer userRoleId;
	private Usuario users;
	private String role;

	public UsuarioRol() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_role_id", unique = true, nullable = false)
	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Usuario getUsers() {
		return this.users;
	}

	public void setUsers(Usuario users) {
		this.users = users;
	}

	@Column(name = "role", nullable = false, length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
